name: Deployment

on:
  push:
    branches:
    - release # change to main if deploying to a website
  
jobs:
  deploy:
    name: Deploy to App Engine
    runs-on: ubuntu-latest
    outputs:
        url: ${{steps.gae.outputs.url}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Google App Engine
        id: gae
        uses: google-github-actions/deploy-appengine@v0.4.0
        with:
          project_id: le-mans-407917
          version: main
          credentials: ${{secrets.GOOGLE_APP_ENGINE_KEY}}
          deliverables: app.yaml
